### ISSUE TITLE
Things to get feedback on: Checkpoint I

### ISSUE THREAD

**Issue by searri** [gwu-iot/20_star-squad#8]
## Peripherals
- Fog machine? Yes or no
- How do we control the fog machine with a Raspberry Pi?
- What style of clock should we have?

## Computing power
- Which Raspberry Pi should we use?
- How Raspberry Pis do we need?
- Can we do sensor processing on the Pi(s) or have separate Arduinos for that purpose?

## Environment
- Should we have red light on globe or in room?
- Beach tent (not as immersive, easier to control) or full tent (more expensive)? Mostly an @gparmer  question

**Comment by tuhinadasgupta** [comment]
tents
beach: more contained
canopy: more immersive
